dependencies:
  #<organization/repo/>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

dotenv: .env

networks:
  rinkeby:
    eth_usdt_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork-dev:
    eth_usdt_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  goerli:
    eth_usdt_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    verify: True
  development:
    verify: False
  local-ganache:
    verify: False